### ISSUE TITLE
scan_interval_seconds not optional

### ISSUE THREAD

**Issue by weidi** [fuslwusl/homeassistant-edl21-custom-interval#1]
Hi,
i tried switching to the custom integration but seems that scan_interval_seconds is a required value instead of beeing optional.

`Invalid config for [sensor.edl21]: expected int for dictionary value @ data['scan_interval_seconds']. Got None. (See /config/configuration.yaml, line 87). Please check the docs at https://www.home-assistant.io/integrations/edl21`

Once added to the config it´s working fine now.

**Comment by fuslwusl** [comment]
Thanx for this info. I will change this with the next update.
