### ISSUE TITLE
Platform schema not functional

### ISSUE THREAD

**Issue by decanyon** [fuslwusl/homeassistant-edl21-custom-interval#2]
With the new update, the platform configuration scheme no longer works. 

According to instructions, the system cannot be made to fly. Code was stored under /config/custom_components/edl21 and the configuration.yaml was adjusted according to the specifications. Hardware used: Hichi USB IR on an RPI3

**Comment by fuslwusl** [comment]
I am using this integration with the latest version and everything is working fine. Just try reinstalling the custom integration and restart ha.
