### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by querys1** [fuslwusl/homeassistant-edl21-custom-interval#3]
Something has changed with the EDL21 configuration and how to add it to the system. After a restart of HA the EDL21-custom is not working anymore and I had to add the "new" variant of the EDL21.
Now I'm back to the 60s update intervall, which is quite annoying for the instant power consumption.

**Comment by fuslwusl** [comment]
It seems that the custom EDL21 integration was overwritten by the original EDL21. Just install the custom version again and it should work. Also check your config. I am using the latest version of HomeAssistant and had no problem.

**Comment by querys1** [comment]
Did you make a restart? It worked with the latest version, until I restarted the HA installation.
![edl21](https://github.com/fuslwusl/homeassistant-edl21-custom-interval/assets/116440848/ffb33545-e886-421a-944c-87ebbfd8050b)

Afterwards I had to use the "official" way with the integration button and the configuration.yaml was not used anymore and the folder unter "custom components" was missing. When adding the scan interval the yaml file it writes an error, that the scan interval option is invalid.
![config](https://github.com/fuslwusl/homeassistant-edl21-custom-interval/assets/116440848/c8609d17-0def-4a01-ba2d-8322491ba8ef)

**Comment by fuslwusl** [comment]
It seems that your system is using the regular integration instead of the custom integration. Try removing the edl21 config and this custom integration and restart. Then add this custom integration folder and restart. As last step add the edl21 config and scan_interval_seconds should be accepted.

**Comment by querys1** [comment]
Thanks a lot. I tried it several ways with a couple of restarts, but now its working again. Thanks for the help!
