### ISSUE TITLE
Setup failed for custom integration edl21: No setup or config entry setup function defined.

### ISSUE THREAD

**Issue by denishol** [fuslwusl/homeassistant-edl21-custom-interval#4]
Your custom component is working, it logs every 10 seconds. But this error is logged in 

> 2023-07-09 16:18:09.010 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration edl21 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2023-07-09 16:19:18.264 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: hassio
> 2023-07-09 16:19:55.682 ERROR (MainThread) [homeassistant.setup] **Setup failed for custom integration edl21: No setup or config entry setup function defined.**
> 

This is my folder structure:

> [core-ssh ~]$ ls /root/config/custom_components/edl21
>``` __init__.py    __pycache__    manifest.json  sensor.py```

I'm wondering, if ```__init__.py``` is correct:
`"""The edl21 component."""`

**Comment by PEngels** [comment]
Unfortunately I am experiencing the same problem..

**Comment by bastian1607** [comment]
Nearly same error:

Logger: homeassistant.setup
Source: setup.py:283 
First occurred: 21:04:30 (1 occurrences) 
Last logged: 21:04:30

Setup failed for custom integration edl21: No setup or config entry setup function defined.

**Comment by fuslwusl** [comment]
I cannot reproduce this. Maybe this is a problem with your configuration? Or there was a change that leads to this error for new installations. If it works just ignore it.
